// Load the correct .env file based on NODE_ENV.
// On ECS the vars are injected by the task definition, so dotenv is a no-op there
// (the files simply don't exist in the container image).
{
  const path = require('path');
  const envFile = process.env.NODE_ENV === 'production' ? '.env.production' : '.env';
  require('dotenv').config({ path: path.resolve(__dirname, envFile) });
}
const express = require('express');
const http = require('http');
const cors = require('cors');
const helmet = require('helmet');
const connectDB = require('./db');
const { apiLimiter, authLimiter, pollLimiter } = require('./middleware/rateLimiter');
const { identifyUser } = require('./middleware/auth');
const gridfsService = require('./services/gridfsService'); // GridFS for ZAP reports
const { startCleanupJob } = require('./jobs/cleanupJob'); // Scheduled cleanup
const {
  initializeSocket,
  initializeScanProgressSubscriber,
  emitScanProgress
} = require('./services/notificationService');
const { setPublisher, setDirectEmitter } = require('./services/scanProgressService');
const { createRedisClient, getPublisher, getSubscriber, checkRedisClientHealth } = require('./config/redis');
const { createScanWorker } = require('./workers/scanWorker');
const { createZapWorker }  = require('./workers/zapWorker');

let inProcessWorker    = null;
let inProcessZapWorker = null;

// IMPORT ZAP ROUTES
const zapRoutes = require('./routes/zapRoutes');
const zapAuthRoutes = require('./routes/zapAuthRoutes');
const webCheckRoutes = require('./routes/webCheckRoutes');

// Validate required environment variables
const requiredEnvVars = ['MONGO_URI', 'JWT_SECRET'];
const missingVars = requiredEnvVars.filter(varName => !process.env[varName]);

if (missingVars.length > 0) {
  console.error('❌ ERROR: Missing required environment variables:');
  missingVars.forEach(varName => console.error(`   - ${varName}`));
  process.exit(1);
}

const app = express();

app.use(helmet({
  // Google OAuth popup needs window.closed access across origins;
  // helmet's default "same-origin" blocks it → use allow-popups variant.
  crossOriginOpenerPolicy: { policy: 'same-origin-allow-popups' },
}));
// Hop count from the app back out to the client, so req.ip resolves to the real
// viewer rather than a proxy.
//
// Verified 2026-08-12: api.fortexa.aevus.jp is a CNAME straight to
// fortexa-alb-…elb.amazonaws.com, and responses carry no CloudFront headers — so
// the API path is ALB -> ECS, exactly ONE trusted hop. (The frontend is behind
// CloudFront; the API is not. infrastructure/api-cloudfront-response-headers.json
// describes a distribution that is not in the live DNS path.)
//
// This value must match the real topology. Too LOW and req.ip is a proxy address,
// so every user shares one rate-limit bucket. Too HIGH and Express trusts one more
// X-Forwarded-For entry than exists — which the client controls, letting anyone
// forge their own rate-limit key. Raise it to 2 only if a CDN is put in front.
const TRUSTED_PROXY_HOPS = Number.parseInt(process.env.TRUSTED_PROXY_HOPS, 10);
app.set('trust proxy', Number.isFinite(TRUSTED_PROXY_HOPS) ? TRUSTED_PROXY_HOPS : 1);

// Comma-separated list in FRONTEND_URL supports multiple production domains,
// e.g. "https://fortexa.aevus.jp"
const defaultFrontendOrigins = ['https://fortexa.aevus.jp'];
const rawFrontendOrigins = process.env.FRONTEND_URL;
if (!rawFrontendOrigins && process.env.NODE_ENV === 'production') {
  console.warn('[CORS] FRONTEND_URL is not set in production; using safe defaults.');
}
const allowedOriginsSet = new Set(
  (rawFrontendOrigins || defaultFrontendOrigins.join(','))
    .split(',').map(o => o.trim()).filter(Boolean)
);
if (process.env.NODE_ENV !== 'production') {
  ['http://localhost:3000', 'http://localhost:3002', 'http://localhost:3003']
    .forEach(o => allowedOriginsSet.add(o));
}

const corsOptions = {
  origin(origin, callback) {
    // Allow server-to-server calls (no Origin header) and known origins
    if (!origin || allowedOriginsSet.has(origin)) return callback(null, true);
    console.warn(`[CORS] Blocked request from: ${origin}`);
    callback(new Error('Not allowed by CORS'));
  },
  credentials: true,
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'x-auth-token', 'Authorization'],
  maxAge: 86400, // cache preflight 24h
};

// Ensure CORS headers are present even when errors are generated by middleware that
// short-circuits the normal response flow (e.g. thrown errors, auth failures).
// NOTE: This cannot affect responses generated upstream by ALB/CloudFront (e.g. 502/504).
function applyCorsToResponse(req, res) {
  const origin = req.headers?.origin;
  if (!origin) return;
  if (!allowedOriginsSet.has(origin)) return;
  res.setHeader('Access-Control-Allow-Origin', origin);
  res.setHeader('Vary', 'Origin');
  res.setHeader('Access-Control-Allow-Credentials', 'true');
}

app.use(cors(corsOptions));
// Explicit preflight handler — must come before rate limiters and routes so
// OPTIONS requests never reach authLimiter or route handlers (which assume a body).
app.options(/.*/, cors(corsOptions));

// ─── STRIPE WEBHOOK — must come BEFORE express.json() ────────────────────────
// Stripe requires the raw body (Buffer) to verify the webhook signature.
// Mounting it here with express.raw() ensures json() middleware is NOT applied.
if (process.env.STRIPE_SECRET_KEY) {
  app.use('/api/stripe/webhook', express.raw({ type: 'application/json' }));
  console.log('✅ Stripe webhook endpoint mounted at /api/stripe/webhook');
}
app.use(express.json({ extended: false, limit: '10mb' }));
app.use(express.urlencoded({ extended: false, limit: '10mb' }));

app.use((req, res, next) => {
  // req.ips shows the full resolved X-Forwarded-For chain — use it to confirm the
  // 'trust proxy' hop count is right for the deployed topology.
  const chain = req.ips?.length ? ` chain: ${req.ips.join(' -> ')}` : '';
  console.log(`${new Date().toISOString()} - ${req.method} ${req.path} - IP: ${req.ip}${chain}`);
  next();
});

// Everything under /api is per-user data behind a bearer token — scan results,
// PDF reports, profile and billing. A shared cache in front of the origin
// (CloudFront, a corporate proxy) that keys on the URL alone would hand one
// customer's report to another, so mark the whole API uncacheable and vary on the
// auth headers. Static assets are served separately and are unaffected.
app.use('/api', (req, res, next) => {
  res.setHeader('Cache-Control', 'no-store, private');
  // res.vary() APPENDS. setHeader() would clobber the `Vary: Origin` that the
  // cors middleware adds, and this API reflects the request Origin — losing it
  // lets a shared cache pair a response with the wrong Access-Control-Allow-Origin.
  res.vary('x-auth-token');
  res.vary('Authorization');
  next();
});

// `identifyUser` must run BEFORE every limiter so keyGenerator sees the caller's
// user id. It never rejects — the per-route `auth` still enforces access.
//
// The scan routers carry browser-driven status polling (PDF job status, scan
// progress), so they get the generous per-user `pollLimiter` as their umbrella.
// The strict `scanLimiter` is applied per-route to the endpoints that actually
// START work — see each router. Previously the strict limiter covered the whole
// router, so ordinary polling exhausted it and downloads began failing.
app.use('/auth', authLimiter, require('./routes/auth'));
app.use('/api/scan', identifyUser, pollLimiter, require('./routes/virustotalRoutes'));
app.use('/api/pagespeed', identifyUser, apiLimiter, require('./routes/pageSpeedRoutes'));

// 👇 REGISTER PROFILE ROUTE
app.use('/api/profile', identifyUser, apiLimiter, require('./routes/profile'));

// 👇 REGISTER STRIPE ROUTES (authenticated plan/checkout endpoints)
if (process.env.STRIPE_SECRET_KEY) {
  app.use('/api/stripe', identifyUser, apiLimiter, require('./routes/stripeRoutes'));
  console.log('✅ Stripe API routes mounted at /api/stripe');
}

// 👇 REGISTER ZAP ROUTE
app.use('/api/zap', identifyUser, pollLimiter, zapRoutes);

// 👇 REGISTER ZAP AUTH ROUTES (Authenticated scanning on port 8081)
app.use('/api/zap-auth', identifyUser, pollLimiter, zapAuthRoutes);

// 👇 REGISTER WEBCHECK ROUTES
app.use('/api/webcheck', identifyUser, pollLimiter, webCheckRoutes);

// 👇 REGISTER TRANSLATE ROUTES (Gemini-powered translation)
app.use('/api/translate', identifyUser, apiLimiter, require('./routes/translateRoutes'));

// 👇 REGISTER URLSCAN ROUTES
app.use('/api/urlscan', identifyUser, apiLimiter, require('./routes/urlscanRoutes'));

// 👇 REGISTER ORGANIZATION ROUTES
app.use('/api/org', identifyUser, apiLimiter, require('./routes/orgRoutes'));

// 👇 REGISTER SCHEDULE + NOTIFICATION ROUTES
app.use('/api/schedules', identifyUser, apiLimiter, require('./routes/scheduleRoutes'));
// Notifications are polled by the browser as a WebSocket fallback.
app.use('/api/notifications', identifyUser, pollLimiter, require('./routes/notificationRoutes'));

// ── /health — lightweight liveness probe (ECS health check target) ───────────
// Returns 200 immediately; ECS uses this to decide whether to route traffic.
// Intentionally minimal — no DB or Redis calls so it never blocks.
app.get('/health', (req, res) => {
  const mem = process.memoryUsage();
  res.status(200).json({
    status:    'healthy',
    timestamp: new Date().toISOString(),
    uptime:    Math.floor(process.uptime()),
    memory: {
      heapUsedMB:  Math.round(mem.heapUsed  / 1048576),
      heapTotalMB: Math.round(mem.heapTotal / 1048576),
      rssMB:       Math.round(mem.rss       / 1048576),
    },
  });
});

// ── /ready — readiness probe (checks dependencies before accepting scan traffic) ─
// ECS Service Connect / ALB can use this to temporarily remove unhealthy tasks.
app.get('/ready', async (req, res) => {
  const checks = {};
  let allReady = true;

  // MongoDB
  const mongoose = require('mongoose');
  const mongoState = mongoose.connection.readyState;
  // 1 = connected, 2 = connecting
  checks.mongodb = { ready: mongoState === 1, state: ['disconnected','connected','connecting','disconnecting'][mongoState] ?? mongoState };
  if (mongoState !== 1) allReady = false;

  // Redis (best-effort — non-blocking ping)
  if (process.env.REDIS_URL) {
    try {
      const { getPublisher } = require('./config/redis');
      const pub = getPublisher();
      if (pub.status === 'ready') {
        let clientStats = {};
        try {
          const info = await pub.info('clients');
          const lines = info.split('\n');
          let connected = 0;
          let max = 0;
          for (const line of lines) {
            if (line.startsWith('connected_clients:')) connected = parseInt(line.split(':')[1].trim(), 10);
            if (line.startsWith('maxclients:')) max = parseInt(line.split(':')[1].trim(), 10);
          }
          clientStats = {
            connected_clients: connected,
            maxclients: max,
            warning: (max > 0 && connected > 0.8 * max) ? 'High connection usage' : undefined
          };
        } catch (_) {}
        checks.redis = { ready: true, status: 'ready', ...clientStats };
      } else {
        checks.redis = { ready: false, status: pub.status };
        allReady = false;
      }
    } catch {
      checks.redis = { ready: false, status: 'unavailable' };
      allReady = false;
    }
  } else {
    checks.redis = { ready: false, status: 'not_configured' };
    allReady = false;
  }

  // WebCheck container (optional — degraded not down)
  try {
    const { checkHealth } = require('./services/webCheckService');
    const webCheckOk = await checkHealth();
    checks.webcheck = { ready: webCheckOk };
    if (!webCheckOk) allReady = false;
  } catch {
    checks.webcheck = { ready: false, status: 'unavailable' };
    allReady = false;
  }

  // Active scan metrics
  try {
    const { getActiveScanCount, getMetrics } = require('./services/webCheckService');
    checks.webCheckScans = {
      active:    getActiveScanCount(),
      ...getMetrics(),
    };
  } catch { /* non-critical */ }

  res.status(allReady ? 200 : 503).json({
    ready:     allReady,
    timestamp: new Date().toISOString(),
    checks,
  });
});

app.get('/', (req, res) => {
  res.status(200).json({ status: 'ok' });
});

app.use((req, res) => {
  applyCorsToResponse(req, res);
  res.status(404).json({ error: 'Not Found', message: `Cannot ${req.method} ${req.path}` });
});

app.use((err, req, res, next) => {
  console.error('❌ Unhandled error:', err);
  applyCorsToResponse(req, res);
  res.status(err.status || 500).json({
    error: 'Internal Server Error',
    message: process.env.NODE_ENV === 'development' ? err.message : 'Something went wrong'
  });
});

const PORT = process.env.PORT || 3000;

// Create HTTP server and attach Socket.IO
const server = http.createServer(app);
initializeSocket(server);

// Graceful shutdown — ECS sends SIGTERM on deploy/scale-in, waits 30s then SIGKILL
const shutdown = (signal) => {
  console.log(`\n${signal} received. Closing server gracefully...`);
  server.close(async () => {
    // Drain in-process worker first so BullMQ releases job locks cleanly.
    if (inProcessWorker) {
      try {
        await inProcessWorker.close();
        inProcessWorker = null;
      } catch (e) {
        console.error('⚠️  Failed to close BullMQ scan worker:', e.message);
      }
    }
    if (inProcessZapWorker) {
      try {
        await inProcessZapWorker.close();
        inProcessZapWorker = null;
      } catch (e) {
        console.error('⚠️  Failed to close BullMQ ZAP worker:', e.message);
      }
    }
    // Drain BullMQ queue connections (scan + zap) before closing Redis singletons
    try {
      const { closeScanQueue } = require('./queues/scanQueue');
      const { closeZapQueue }  = require('./queues/zapQueue');
      await Promise.all([closeScanQueue(), closeZapQueue()]);
    } catch (_) {}
    // Close Redis singleton connections cleanly
    try {
      const { disconnectAll } = require('./config/redis');
      await disconnectAll();
    } catch (_) {}
    // Release keep-alive socket pool so ECS task terminates cleanly
    try {
      const { destroyHttpClient } = require('./utils/httpClient');
      destroyHttpClient();
    } catch (_) {}
    console.log('✅ HTTP server closed. Exiting.');
    process.exit(0);
  });
  // Force-exit if server hasn't closed within 25s (before ECS sends SIGKILL at 30s)
  setTimeout(() => {
    console.error('⚠️  Graceful shutdown timed out. Forcing exit.');
    process.exit(1);
  }, 25000);
};
process.on('SIGTERM', () => shutdown('SIGTERM'));
process.on('SIGINT', () => shutdown('SIGINT'));

process.on('unhandledRejection', (reason) => {
  console.error('❌ Unhandled Promise Rejection:', reason);
});
process.on('uncaughtException', (err) => {
  console.error('💥 Uncaught Exception:', err);
  shutdown('uncaughtException');
});

async function startServer() {
  try {
    await connectDB();

    try {
      gridfsService.initialize('zap_reports');
      gridfsService.initialize('zap_auth_reports');
      gridfsService.initialize('webcheck_results');
      console.log('✅ GridFS initialized (buckets: zap_reports, zap_auth_reports, webcheck_results)');
    } catch (error) {
      console.error('⚠️  GridFS initialization failed:', error.message);
      console.error('   Large file storage may not work properly');
    }

    try {
      startCleanupJob();
      console.log('✅ Cleanup job scheduler started');
    } catch (error) {
      console.error('⚠️  Cleanup job initialization failed:', error.message);
    }

    // ── Redis + real-time scan progress ──────────────────────────────────
    if (process.env.REDIS_URL) {
      try {
        // Run Redis client count/health check on startup
        await checkRedisClientHealth();

        // Publisher: used by scanProgressService to broadcast progress events
        const publisher = getPublisher();
        setPublisher(publisher);

        // Direct in-process emitter — avoids Redis round-trip when worker runs
        // in the same process as the server (the default single-container mode)
        setDirectEmitter((scanId, userId, data) => emitScanProgress(scanId, userId, data));

        // Subscriber: receives events published by standalone worker processes
        // and forwards them to Socket.IO rooms
        const subscriber = getSubscriber();
        initializeScanProgressSubscriber(subscriber);

        console.log('✅ Redis pub/sub connected (scan progress channel active)');

        // Start in-process BullMQ worker unless an external worker is running
        // (set DISABLE_WORKER=true when deploying a dedicated worker ECS task)
        if (process.env.DISABLE_WORKER !== 'true') {
          inProcessWorker    = createScanWorker(publisher);
          inProcessZapWorker = createZapWorker(publisher);
          console.log('✅ In-process BullMQ scan + ZAP workers started');

          // Confirm the task role can actually reach ECS. Without this check a missing
          // IAM policy stays invisible until the first scan of the day fails on recycle.
          // Deliberately not awaited — this must never block or fail startup.
          const { preflightEcsAccess } = require('./services/zapRecycler');
          preflightEcsAccess().catch(err =>
            console.error('[ZapRecycle] preflight threw unexpectedly:', err.message)
          );
        } else {
          console.log('ℹ️  DISABLE_WORKER=true — expecting external worker process');
        }
      } catch (redisErr) {
        console.error('⚠️  Redis connection failed:', redisErr.message);
        console.error('   Real-time scan progress will be unavailable.');
        console.error('   Set REDIS_URL to enable WebSocket scan updates.');
      }
    } else {
      console.warn('⚠️  REDIS_URL not set — WebSocket scan progress and BullMQ disabled.');
      console.warn('   Scans will NOT run. Please set REDIS_URL in your environment.');
    }

    server.listen(PORT, '0.0.0.0', () => {
      console.log('\n=================================');
      console.log('🚀 Server started successfully!');
      console.log(`📡 Listening on port ${PORT}`);
      console.log('🔌 Socket.IO notifications enabled');
      if (process.env.REDIS_URL) {
        console.log('⚡ Real-time scan progress via WebSocket enabled');
      }
      console.log('=================================\n');
    });

  } catch (err) {
    console.error(' Fatal: could not connect to MongoDB on startup:', err.message);
    process.exit(1);
  }
}

startServer();
